### ISSUE TITLE
Not working in the Ember's Production Environment

### ISSUE THREAD

**Issue by gowthamrm** [201-created/ember-inline-css#9]
CSS inlining is not working with the ember production build, it is working fine with the development build though.

**Reproduction**:
Tried `ember-inline-css` addon in this ember addon repo ([ember-scroll-preview](https://github.com/gowthamrm/ember-scroll-preview)). CSS got inlined properly in the development, but failed with the production environment (`ember build --environment=production`).

**Comment by gowthamrm** [comment]
@rondale-sc The regex used to match and replace the css files does not work well with the fingerprinted assets. Have fixed the same in this [PR](https://github.com/201-created/ember-inline-css/pull/10). Please do have a look.

**Comment by sohara** [comment]
In our app we are excluding the css assets to be in-lined from fingerprinting, as described here: https://ember-cli.com/asset-compilation#fingerprinting-and-cdn-urls

I wonder if this would solve the issue and obviate the PR? Either way, might be good to mention it in the readme?

**Comment by rondale-sc** [comment]
@gowthamrm Sorry, musta missed this.  I can tell you that I have this code such as it is in place on a few production sites.  If I get free I'm going to try to boot your repro.

**Comment by steveszc** [comment]
Can confirm @sohara's suggestion that excluding the inlined css file from fingerprinting is a work around for this issue.
